### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mathewcst** [mathewcst/the-perfect-webapp#1]
## Estrutura do projeto:

- [x] Estrutura básica (`create-nuxt-app`)
- [x] Libs
  - [x] [Vue aXe](https://github.com/vue-a11y/vue-axe) (a11y)
  - [x] [Nuxt Optimized Images](https://github.com/bazzite/nuxt-optimized-images) (otimização)
  - [x] [Component Cache](https://github.com/nuxt-community/modules/tree/master/packages/component-cache) (otimização)
  - [x] [Sitemap](https://github.com/nuxt-community/sitemap-module) (SEO)
  - [x] [Google Analytics](https://github.com/nuxt-community/analytics-module)

## Funcionalidades
O webapp será uma simples to-do list com duas páginas internas: Sobre e Contato. Acho que é o suficiente pra simular uma webapp simples.
- [ ] Home
  - [ ] Listar ToDos
  - [ ] CRUD de tarefas
- [ ] Sobre
  - [ ] Conteúdo sobre o propósito do projeto com referências
- [ ] Contato
  - [ ] Links para redes sociais
